"""add stakeholders table

Revision ID: be42e0c48bb1
Revises: 12d21703fcf1
Create Date: 2026-06-29 06:00:45.457097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be42e0c48bb1'
down_revision = '12d21703fcf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stakeholders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'property_manager', 'tenant', name='stakeholder_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'role', name='uq_stakeholders_property_role')
    )
    op.create_index(op.f('ix_stakeholders_company_id'), 'stakeholders', ['company_id'], unique=False)
    op.create_index(op.f('ix_stakeholders_id'), 'stakeholders', ['id'], unique=False)
    op.create_index(op.f('ix_stakeholders_property_id'), 'stakeholders', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stakeholders_property_id'), table_name='stakeholders')
    op.drop_index(op.f('ix_stakeholders_id'), table_name='stakeholders')
    op.drop_index(op.f('ix_stakeholders_company_id'), table_name='stakeholders')
    op.drop_table('stakeholders')
    # ### end Alembic commands ###

