"""add estimates table

Revision ID: ca04d9753c98
Revises: 046d6ba65122
Create Date: 2026-06-29 06:19:37.201970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca04d9753c98'
down_revision = '046d6ba65122'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('system_size_kw', sa.Numeric(), nullable=True),
    sa.Column('price_per_watt', sa.Numeric(), nullable=True),
    sa.Column('system_losses_pct', sa.Numeric(), nullable=True),
    sa.Column('shading_pct', sa.Numeric(), nullable=True),
    sa.Column('annual_consumption_kwh', sa.Numeric(), nullable=True),
    sa.Column('blended_utility_rate', sa.Numeric(), nullable=True),
    sa.Column('rate_escalation_pct', sa.Numeric(), nullable=True),
    sa.Column('include_bess', sa.Boolean(), nullable=True),
    sa.Column('incentives', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('annual_production_kwh', sa.Numeric(), nullable=True),
    sa.Column('system_cost', sa.Numeric(), nullable=True),
    sa.Column('net_cost', sa.Numeric(), nullable=True),
    sa.Column('annual_savings', sa.Numeric(), nullable=True),
    sa.Column('savings_20yr', sa.Numeric(), nullable=True),
    sa.Column('irr', sa.Numeric(), nullable=True),
    sa.Column('npv', sa.Numeric(), nullable=True),
    sa.Column('simple_payback_years', sa.Numeric(), nullable=True),
    sa.Column('co2_offset_20yr', sa.Numeric(), nullable=True),
    sa.Column('google_solar_raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estimates_id'), 'estimates', ['id'], unique=False)
    op.create_index(op.f('ix_estimates_property_id'), 'estimates', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estimates_property_id'), table_name='estimates')
    op.drop_index(op.f('ix_estimates_id'), table_name='estimates')
    op.drop_table('estimates')
    # ### end Alembic commands ###

