"""Add properties table

Revision ID: da03e2b4a472
Revises: 98e9f3efef29
Create Date: 2026-06-29 05:39:23.434043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da03e2b4a472'
down_revision = '98e9f3efef29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('lat', sa.Numeric(), nullable=True),
    sa.Column('lon', sa.Numeric(), nullable=True),
    sa.Column('solar_rooftop_area', sa.Numeric(), nullable=True),
    sa.Column('building_area', sa.Numeric(), nullable=True),
    sa.Column('parcel_area', sa.Numeric(), nullable=True),
    sa.Column('stories', sa.Integer(), nullable=True),
    sa.Column('zoning', sa.String(), nullable=True),
    sa.Column('parcel_use', sa.String(), nullable=True),
    sa.Column('apn', sa.String(), nullable=True),
    sa.Column('structure_year_built', sa.Integer(), nullable=True),
    sa.Column('total_parcel_value', sa.Numeric(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_external_id'), 'properties', ['external_id'], unique=False)
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_external_id'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###

